//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTrackerJS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppCode
    {
        public int ID { get; set; }
        public string CodeType { get; set; }
        public string CodeValue { get; set; }
        public string CodeText { get; set; }
        public bool ActiveFlag { get; set; }
    }
}
