//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTrackerJS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SaleLines = new HashSet<SaleLine>();
        }
    
        public int ID { get; set; }
        public string UserNameAddressee { get; set; }
        public System.DateTime SaleDate { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> PaymentApproved { get; set; }
        public Nullable<decimal> ApprovedAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleLine> SaleLines { get; set; }
    }
}
