//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTrackerJS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string DNI { get; set; }
        public string CBU { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
    }
}
